### PR TITLE
Fix message base having incorrect orig / dest addresses

### PR DESCRIPTION
**Pull request by ghost**
When forwarding messages to downlinks, it changes the origin address and destination address to suit the downlink, but the changes are then saved into the local message base.

This change saves the original addresses, changes them for the downlinks, then restores the original addresses after writing to the packet.

### CODE REVIEW

**Comment by dukelsky** [comment]
Please describe in detail how to reproduce the bug

**Comment by ghost** [comment]
1. receive mail from uplink to host
2. send mail from host to downlinks
3. look at dest / orig addresses in message base on host

This is using squish message bases, though I don't think that matters in triggering the bug.

**Comment by dukelsky** [comment]
I use squish for some echo message bases and originating addresses are correct there. Destination address is not used for echo areas. Maybe you looked into a wrong field. A frame starts with 53 44 AE AF signature (in Intel reverse order), so the byte with 53 has the offset of 0. The originating address has offset of 176 decimal. And do not forget that the four two-byte address words are in the reverse order.

**Comment by ghost** [comment]
Yes, but do you have a downlink? When tossing, first HPT sends to downlinks, it passes a pointer to a message structure, that message structure the originating address is altered to save the packet for the downlink, so when it returns from the downlink function, the message structure has changed and it is saved in it's changed state to the message base. 

If you do not have a downlink then the message structure is not changed and the originating address is correct in the message base.

**Comment by dukelsky** [comment]
I have 51 links in the echo I have checked. Is it enough?

**Comment by ghost** [comment]
Yes, you only need one link to make it exhibit this behaviour. What are you expecting the originating address to be? 

For me, when I do not have this patch applied, my message base shows my node as the originating address, instead of the node the message actually came from - but only if I have a downlink.

**Comment by ghost** [comment]
This code here in forwardToLinks alters the s_message structure it is passed 

        msg->destAddr = header.destAddr;
        /*  .. and must come from us */
        msg->origAddr = header.origAddr;


        rc += writeMsgToPkt(newLinks[i]->link->pkt, *msg);

So when it returns to forwardMsgToLinks, then to processEMMessage the structure has been altered, it then proceeds to Save that message structure in when it calls putMsgInArea.

**Comment by ghost** [comment]
It could be working for you if dontdocc is unset, as that uses a copy of the message

*edit: hmm, or perhaps my HPT is returning null from MessForCC, I haven't set anything to do with carbon copys in my config.

**Pull request closed without merging**
