### PR TITLE
if present, use the original DateTime string when exporting to a packet

### PR DESCRIPTION
**Pull request by zoomosis**

### CODE REVIEW

**Comment by streaps** [comment]
This PR would close issue #18

**Comment by askovpen** [comment]
это не после этого патча такие пакеты хпт начало создавать?
(в поле дата какая-то хрень)

image

**Comment by zoomosis** [comment]
The junk in the date field is because this patch wasn't merged:

https://github.com/huskyproject/smapi/pull/14

**Comment by dukelsky** [comment]
Sorry, I missed it for some reason. Merged now.

**Comment by zoomosis** [comment]
Thanks :)

**Pull request merged**
